import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './globals.css';

const inter = Noto_Sans({
	subsets: ['latin'],
	weight: ['300', '400', '600', '500', '700']
});

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app'
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body className={inter.className}>{children}</body>
		</html>
	);
}
