import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './styles/globals.css';
import cn from 'classnames';
import styles from './styles/layout.module.css';
import { Footer, Header, Sidebar } from './page-components';
import { Up } from '@/components';
import { SkipLink } from './page-components/SkipLink/SkipLink';
import { OpengraphTags } from '@/helpers/opengraph';

const inter = Noto_Sans({
	subsets: ['latin', 'cyrillic'],
	weight: ['300', '400', '600', '500', '700']
});

// export async function generateMetadata({
// 	router
// }: AppProps): Promise<Metadata> {
// 	return {
// 		title: 'Create Next App',
// 		description: 'Generated by create next app',
// 		metadataBase: new URL(process.env.NEXT_PUBLIC_DOMIAN),
// 		openGraph: {
// 			url: process.env.NEXT_PUBLIC_DOMIAN + '/' ,
// 			locale: 'ru_Ru',
// 			type: 'article'
// 		}
// 	};
// }

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
	metadataBase: new URL(process.env.NEXT_PUBLIC_DOMIAN),
	openGraph: {
		...OpengraphTags
	}
};

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body className={cn(inter.className, styles['wrapper'])}>
				<Header className={styles['header']}>
					<Sidebar />
				</Header>
				<Sidebar className={styles['sidebar']} />
				<SkipLink className={styles['body']}>{children}</SkipLink>
				<Footer className={styles['footer']} />
				<Up />
			</body>
		</html>
	);
}
