import type { Metadata } from 'next';
import { Noto_Sans } from 'next/font/google';
import './styles/globals.css';
import cn from 'classnames';
import styles from './styles/layout.module.css';
import { Footer, Header, Sidebar } from './page-components';
import { Up } from '@/components';
import { SkipLink } from './page-components/SkipLink/SkipLink';
import { OpengraphTags } from '@/helpers/opengraph';
import Script from 'next/script';
import YandexMetrika from '@/components/YandexMetrika/YandexMetrika';

const inter = Noto_Sans({
	subsets: ['latin', 'cyrillic'],
	weight: ['300', '400', '600', '500', '700']
});

export async function generateMetadata(): Promise<Metadata> {
	const urlPath = process.env.NEXT_PUBLIC_DOMIAN;
	return {
		title: 'Create Next App',
		description: 'Generated by create next app',
		metadataBase: new URL(urlPath ? urlPath : ''),
		openGraph: {
			...OpengraphTags
		}
	};
}

export default function RootLayout({
	children
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="ru">
			<body className={cn(inter.className, styles['wrapper'])}>
				<Script id="metrika-counter" strategy="afterInteractive">
					{`(function(m,e,t,r,i,k,a){m[i]=m[i]||function(){(m[i].a=m[i].a||[]).push(arguments)};
              m[i].l=1*new Date();
              for (var j = 0; j < document.scripts.length; j++) {if (document.scripts[j].src === r) { return; }}
              k=e.createElement(t),a=e.getElementsByTagName(t)[0],k.async=1,k.src=r,a.parentNode.insertBefore(k,a)})
              (window, document, "script", "https://mc.yandex.ru/metrika/tag.js", "ym");
 
              ym("init", {
                    defer: true,
                    clickmap:false,
                    trackLinks:true,
                    accurateTrackBounce:true,
                    webvisor:true
              });`}
				</Script>
				<YandexMetrika />
				<Header className={styles['header']}>
					<Sidebar />
				</Header>
				<Sidebar className={styles['sidebar']} />
				<SkipLink className={styles['body']}>{children}</SkipLink>
				<Footer className={styles['footer']} />
				<Up />
			</body>
		</html>
	);
}
